---

# Playbook to setup ssh keys on hosts

- name: Distribute ssh keys to host and perform keyscan
  hosts: all
  remote_user: svc_ansible
  become: yes # Allows privilege escalation
  gather_facts: true

  tasks:
    - setup-ansible